# Generated by Django 5.0.4 on 2024-09-24 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.ManyToManyField(related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
