# Generated by Django 5.0.4 on 2025-01-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_remove_faq_answer_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
