# Generated by Django 5.0.4 on 2025-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_personality_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
